#!/bin/sh
set -eu

secrets_dir=/run/secrets

# OMP accepts environment credentials for these providers. Filenames must be
# exact environment variable names (case-insensitive); unrelated files are
# ignored. GOOGLE_APPLICATION_CREDENTIALS is the one path-valued exception:
# its secret file is passed as the credential-file path, not as file contents.
supported_secret() {
    case "$1" in
        AIAND_API_KEY|ALIBABA_CODING_PLAN_API_KEY|ALIBABA_TOKEN_PLAN_API_KEY|AIMLAPI_API_KEY|ANTHROPIC_API_KEY|ANTHROPIC_FOUNDRY_API_KEY|ANTHROPIC_OAUTH_TOKEN|AWS_ACCESS_KEY_ID|AWS_BEARER_TOKEN_BEDROCK|AWS_PROFILE|AWS_SECRET_ACCESS_KEY|AZURE_OPENAI_API_KEY|BAILIAN_TOKEN_PLAN_API_KEY|BASETEN_API_KEY|BRAVE_API_KEY|CEREBRAS_API_KEY|CHARM_HYPER_API_KEY|CLOUDFLARE_ACCOUNT_ID|CLOUDFLARE_AI_GATEWAY_API_KEY|CLOUDFLARE_GATEWAY_ID|CLINE_API_KEY|COPILOT_GITHUB_TOKEN|COREWEAVE_API_KEY|COREWEAVE_PROJECT|CURSOR_ACCESS_TOKEN|DEEPINFRA_API_KEY|DEEPSEEK_API_KEY|DEVIN_API_KEY|EXA_API_KEY|FIRECRAWL_API_KEY|FIREPASS_API_KEY|FIREWORKS_API_KEY|FUGU_API_KEY|GEMINI_API_KEY|GITLAB_TOKEN|GMI_API_KEY|GOOGLE_APPLICATION_CREDENTIALS|GOOGLE_CLOUD_API_KEY|GOOGLE_CLOUD_LOCATION|GOOGLE_CLOUD_PROJECT|GROQ_API_KEY|HF_TOKEN|HINDSIGHT_API_TOKEN|HINDSIGHT_API_URL|HUGGINGFACE_HUB_TOKEN|HYPER_API_KEY|JINA_API_KEY|KAGI_API_KEY|KILO_API_KEY|KIMI_API_KEY|LITELLM_API_KEY|LITELLM_BASE_URL|LLAMA_CPP_API_KEY|MINIMAX_API_KEY|MINIMAX_CODE_API_KEY|MINIMAX_CODE_CN_API_KEY|MISTRAL_API_KEY|MODEL_API_KEY|MOONSHOT_API_KEY|NANO_GPT_API_KEY|NVIDIA_API_KEY|NOVITA_API_KEY|OLLAMA_API_KEY|OLLAMA_BASE_URL|OLLAMA_CLOUD_API_KEY|OLLAMA_HOST|OPENAI_API_KEY|OPENAI_CODEX_OAUTH_TOKEN|OPENROUTER_API_KEY|OPENCODE_API_KEY|PARALLEL_API_KEY|PERPLEXITY_API_KEY|QIANFAN_API_KEY|QWEN_OAUTH_TOKEN|QWEN_PORTAL_API_KEY|SAKANA_API_KEY|SILICONFLOW_API_KEY|SILICONFLOW_CN_API_KEY|SYNTHETIC_API_KEY|TAVILY_API_KEY|TINYFISH_API_KEY|TOGETHER_API_KEY|UMANS_AI_CODING_PLAN_API_KEY|VENICE_API_KEY|VERCEL_AI_GATEWAY_API_KEY|VLLM_API_KEY|WAFER_SERVERLESS_API_KEY|WANDB_API_KEY|XAI_API_KEY|XAI_OAUTH_TOKEN|XIAOMI_API_KEY|XIAOMI_TOKEN_PLAN_AMS_API_KEY|XIAOMI_TOKEN_PLAN_CN_API_KEY|XIAOMI_TOKEN_PLAN_SGP_API_KEY|ZAI_API_KEY|ZENMUX_API_KEY|ZHIPU_API_KEY|ZHIPU_CODING_PLAN_API_KEY)
            return 0 ;;
        *) return 1 ;;
    esac
}

if [ -d "$secrets_dir" ]; then
    for secret in "$secrets_dir"/*; do
        [ -f "$secret" ] || continue
        name=${secret##*/}
        # Accept the documented lowercase filenames as well as canonical names.
        normalized=$(printf '%s' "$name" | tr '[:lower:].-' '[:upper:]__')
        supported_secret "$normalized" || continue
        case "$normalized" in
            GOOGLE_APPLICATION_CREDENTIALS)
                export GOOGLE_APPLICATION_CREDENTIALS="$secret"
                ;;
            *)
                value=$(cat "$secret")
                export "$normalized=$value"
                ;;
        esac
    done
fi

exec /usr/local/bin/omp "$@"
